### ISSUE TITLE
Not working with native c# dll.

### ISSUE THREAD

**Issue by mrzaxaryan** [trungnt2910/MemoryModule.NET#33]
Hi c# /net 7/ dll compiled with [NativeAOT](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/) seems not working.
I got System.AccessViolationException.

**Comment by trungnt2910** [comment]
Can you provide more details?

Is the `MemoryModule.NET` itself compiled with NativeAOT, or is the `.dll` you're trying to load compiled?

Furthermore, you might want to check if the `.dll` works with the original [MemoryModule](https://github.com/fancycode/MemoryModule) or provide me with a sample that I can check. Some limitations that apply to the original MemoryModule also applies to MemoryModule.NET, such as the inability to load binaries that uses TLS (thread-local storage).

A stack trace of the exception would also be appreciated.

**Comment by mrzaxaryan** [comment]
[repro](https://github.com/mrzaxaryan/MemoryModule.NET-repro)

**Comment by mrzaxaryan** [comment]
Yes it was TLS (thread-local storage) issue. After compiling using "/Zc:threadSafeInit-" switch all works.
